# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98a0f5f2f9781cd2104b4bfa7872c5e31769cf7fdcb8ff16efbb9463715e74df68ac7370269e1689ffa339d3f44c871db26f9896d15413280f0dc70f12b9cce5

test:
  secret_key_base: 26ac052eaf6dbdb8dbc11c04da9d582bb2b23be8278c1a294a6d2d2587574479431fe6e9ebcc3c78ebcd7988832bf3bd3b111c54d2fd17bcb4f5009bd3e72362

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
